namespace: krateo-system
global:
  compositionId: compositionId
  compositionApiVersion: compositionApiVersion
  compositionResource: compositionResource
mlflow:
  experiment:
    name: diabetes-training-exp1