apiVersion: krateo.io/v1alpha1
kind: Patch
metadata:
  name: composition-{{ .Release.Name }}-tabpane-overview-row-column-1-panel-paragraph-experiment
spec:
  from:
    objectReference:
      apiVersion: mlflow.krateo.io/v1alpha1
      kind: Experiment
      name: {{ .Release.Name }}-mlflow-scaffolding-experiment
      namespace: {{ .Release.Namespace }}
    fieldPath: status
  to:
    objectReference:
      apiVersion: templates.krateo.io/v1alpha1
      kind: Widget
      name: composition-{{ .Release.Name }}-tabpane-overview-row-column-1-panel-paragraph-experiment
      namespace: {{ .Release.Namespace }}
    fieldPath: spec.app.template.text
    transform: >
      ${ "Experiment: https://ml.azure.com/experiments/id/"+ .experiment_id + "?wsid=/subscriptions/31a6f7f0-996a-490e-b431-25c3f54b08b5/resourceGroups/mlops-mlflow/providers/Microsoft.MachineLearningServices/workspaces/MLOps&tid=d2841a2c-2eb6-4f6d-975f-c57c6d2fef5b" }