apiVersion: krateo.io/v1alpha1
kind: Patch
metadata:
  name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-1-tabledata
spec:
  from:
    objectReference:
      apiVersion: templates.krateo.io/v1alpha1
      kind: Widget
      name: composition-{{ .Release.Name }}-card
      namespace: {{ .Release.Namespace }}
    fieldPath: metadata
  to:
    objectReference:
      apiVersion: templates.krateo.io/v1alpha1
      kind: Widget
      name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-1-tabledata
      namespace: {{ .Release.Namespace }}
    fieldPath: spec.api[0].path
    transform: ${ /apis/mlflow.krateo.io/v1alpha1/namespaces/" + .uid + "/runs/" }