---
kind: ConfigMap
apiVersion: v1
metadata:
  name: composition-{{ .Release.Name }}-card
  namespace: {{ .Release.Namespace }}
data:
  panel: "false"
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: composition-{{ .Release.Name }}-card
  namespace: {{ .Release.Namespace }}
spec:
  type: card
  propsRef:
    name: composition-{{ .Release.Name }}-card
    namespace: {{ .Release.Namespace }}
  actions:
  - template:
      apiVersion: templates.krateo.io/v1alpha1
      resource: collections
      name: composition-{{ .Release.Name }}-tablist
      namespace: {{ .Release.Namespace }}
      verb: GET
  - template:
      apiVersion: {{ .Values.global.compositionApiVersion }}
      resource: {{ .Values.global.compositionResource }}
      name:  {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      verb: DELETE
  app:
    template:
      tags: {{ .Release.Namespace }}
      title: {{ .Release.Name }}
      content: This is a card for {{ .Release.Name }} Model scaffolding
      icon: fa-chart-simple
      color: blue
