---
kind: ConfigMap
apiVersion: v1
metadata:
  name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-1-tabledata
  namespace: {{ .Release.Namespace }}
data:
  pageSize: "10"
  columns: "[ {\"key\": \"experiment_name\", \"title\": \"experiment_name\"},{ \"key\": \"run_id\", \"title\": \"run_id\" },{ \"key\": \"metrics\", \"title\": \"metrics\"},{\"key\": \"date\", \"title\": \"date\"} ]"    
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
    name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-1-tabledata
    namespace: {{ .Release.Namespace }}
spec:
  type: tabledata
  propsRef:
    name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-1-tabledata
    namespace: {{ .Release.Namespace }}
  app:
    template:
      data: >
        ${ [.allMetrics.items[] | select(.spec.experiment_name == "{{ .Release.Name }}") | { key: .metadata.uid, experiment_name: "{{ .Release.Name }}", run_id: .spec.run_id, metrics: .status.metrics, date: .metadata.creationTimestamp } ] }
  api:
  - name: allMetrics
    path: "/list?category=metric"
    verb: GET
    endpointRef:
      name: bff-endpoint
      namespace: krateo-system
    headers:
    - 'Accept: application/json'